spring.application.name=EventRentals
server.port=8080

# Admin keys
aws.access.key.id=my-aws-id
aws.secret.access.key=my-aws-access-key
aws.region=us-east-2

# AWS S3
s3.bucket.name.products=products-bucket-final-touch
s3.bucket.name.reservations=reservations-bucket-final-touch

# AWS DynamoDB
dynamodb.endpoint=http://localhost:8000

# Disable default data source initialization
spring.datasource.initialize=false
spring.datasource.url=  # Leave this blank if you're not using a relational database
spring.jpa.hibernate.ddl-auto=none  # Disable Hibernate schema generation

# Logging
logging.file.name=logs/springboot.log
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=DEBUG